apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tw-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: teamwork.local
    http:
      paths:
      # Shell - Contenedor principal de microfrontends
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tw-shell-service
            port: 
              number: 80
      
      # Microfrontend de Autenticaci√≥n
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: tw-auth-service
            port: 
              number: 80
      
      # Microfrontend de Chat
      - path: /chat
        pathType: Prefix
        backend:
          service:
            name: tw-chat-service
            port: 
              number: 80
      
      # Microfrontend de Documentos
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: tw-docs-service
            port: 
              number: 80
      
      # Microfrontend de Tareas
      - path: /tasks
        pathType: Prefix
        backend:
          service:
            name: tw-tasks-service
            port: 
              number: 80

