apiVersion: apps/v1
kind: Deployment
metadata:
  name: tw-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tw-docs
  template:
    metadata:
      labels:
        app: tw-docs
    spec:
      containers:
      - name: tw-docs
        image: tw-docs:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 83
          name: health
---
apiVersion: v1
kind: Service
metadata:
  name: tw-docs-service
  labels:
    app: tw-docs
spec:
  type: NodePort 
  selector:
    app: tw-docs
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30083
    protocol: TCP
    name: http